language: ruby
rvm:
- "2.4"
- "2.5"
- "2.6"
- ruby-head
- jruby-head
cache: bundler
after_script: bundle exec codeclimate-test-reporter
matrix:
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-head
  fast_finish: true
